/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.fkorotkov.gradle.infer

import com.intellij.psi.PsiManager
import com.intellij.testFramework.fixtures.LightJavaCodeInsightFixtureTestCase
import kotlin.io.path.ExperimentalPathApi
import kotlin.io.path.Path
import kotlin.test.Test

class AppTest : LightJavaCodeInsightFixtureTestCase() {
    @ExperimentalPathApi
    @Test
    fun testGeneration() {
        val psiManager = PsiManager.getInstance(project)
        generate(psiManager, Path("/Users/fedor/workspace/cirrus-ci"))
    }
}
